apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-todo
  template:
    metadata:
      labels:
        app: node-todo
    spec:
      containers:
        - name: node-todo
          image: bannouriwalid/node-todo-safe:latest  
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: MONGO_URI
          ports:
            - containerPort: 3000